import { mkdir, readFile, writeFile, copyFile, readdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { affiliateLinks, serviceNames } from '../config/links.mjs';

export const projectRoot = fileURLToPath(new URL('../', import.meta.url));
export const publicImages = [
  'hero-globe.webp', 'streaming-tv.webp', 'feature-speed.webp', 'feature-ai.webp',
  'feature-streaming.webp', 'feature-security.webp', 'ipequal-icon.webp', 'tag-icon.webp',
  'ssrdog-icon.webp', 'lightning-cat-icon.webp', 'fat-cat-icon.webp',
  'youtube-logo.webp', 'netflix-logo.webp', '4k-logo.webp', 'favicon.png',
];
export const brandFiles = ['chatgpt.svg', 'claude.svg', 'cursor.svg', 'claude-code.svg',
  'gemini.svg', 'arrow-right.svg', 'arrow-up.svg', 'shield-check.svg', 'shield-outline.svg',
  'circle-check.svg', 'shield-lock.svg', 'LICENSE', 'TABLER-LICENSE'];
export const publicFiles = [
  'index.html', 'styles.css', 'script.js',
  ...publicImages.map(file => `img/${file}`),
  ...brandFiles.map(file => `img/brands/${file}`),
];

export function normalizeSiteUrl(value = '') {
  if (!value) return '';
  let url;
  try { url = new URL(value); } catch { throw new Error('SITE_URL must be a valid HTTPS origin.'); }
  if (url.protocol !== 'https:' || url.username || url.password || url.port ||
      url.search || url.hash || url.pathname !== '/' ||
      !/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(url.hostname) ||
      /(?:^|\.)(localhost|local|test|invalid)$/i.test(url.hostname)) {
    throw new Error('SITE_URL must be a public HTTPS domain without a path, port, query, or fragment.');
  }
  return url.origin;
}

export function renderHtml(source, siteUrl = '') {
  const origin = normalizeSiteUrl(siteUrl);
  if (!origin) return source;
  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'WebSite', '@id': `${origin}/#website`, name: '2026 VPN 推荐与机场推荐', url: `${origin}/`, inLanguage: 'zh-CN' },
      { '@type': 'CollectionPage', '@id': `${origin}/#page`, url: `${origin}/`, name: '2026 VPN 推荐与机场推荐｜中国用户科学上网选购指南', inLanguage: 'zh-CN',
        isPartOf: { '@id': `${origin}/#website` },
        mainEntity: { '@type': 'ItemList', itemListOrder: 'https://schema.org/ItemListUnordered', numberOfItems: 5,
          itemListElement: Object.entries(serviceNames).map(([slug, name], index) => ({
            '@type': 'ListItem', position: index + 1, name,
            url: `${origin}/#${({ 'lightning-cat': 'lightning', 'fat-cat': 'fatcat' })[slug] || slug}-name`,
          })),
        },
      },
    ],
  };
  return source.replace('content="noindex, nofollow"', 'content="index, follow, max-image-preview:large"')
    .replace('<!-- production-seo -->', [
      `<link rel="canonical" href="${origin}/">`,
      `<meta property="og:url" content="${origin}/">`,
      `<meta property="og:image" content="${origin}/img/hero-globe.webp">`,
      '<meta property="og:image:width" content="1000">',
      '<meta property="og:image:height" content="750">',
      '<meta property="og:image:alt" content="浅蓝色地球与全球网络连接">',
      `<meta name="twitter:image" content="${origin}/img/hero-globe.webp">`,
      `<script type="application/ld+json">${JSON.stringify(structuredData).replace(/</g, '\\u003c')}</script>`,
    ].join('\n  '));
}

export function renderRedirectLocations() {
  const goLocations = Object.entries(affiliateLinks).flatMap(([slug, target]) => {
    if (!target.startsWith('https://') || /["\n\r$\\]/.test(target)) throw new Error(`Unsafe redirect configuration: ${slug}`);
    return [`/go/${slug}`, `/go/${slug}/`].map(route => `    location = ${route} {
        add_header Cache-Control "no-store" always;
        add_header X-Robots-Tag "noindex, nofollow" always;
        return 302 "${target}";
    }`);
  }).join('\n\n');
  return `${goLocations}\n\n    location ^~ /go/ { return 404; }\n`;
}

export function renderNginx(siteUrl = '') {
  const origin = normalizeSiteUrl(siteUrl);
  const host = origin ? new URL(origin).hostname : '_';
  return `# Generated by npm run build. Install in the Nginx http context.
# TLS is configured by your reverse proxy / certificate manager; see deploy/README.md.
server {
    listen 80;
    server_name ${host};
    root /var/www/vpn-selection;
    index index.html;
    charset utf-8;
    server_tokens off;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "DENY" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" always;
${origin ? '' : '    add_header X-Robots-Tag "noindex, nofollow" always;\n'}
    location = / { try_files /index.html =404; expires -1; }
    location = /index.html { return 308 /; }
    location / { try_files $uri =404; }
    location ~* \\.(?:css|js|webp|png|svg)$ { try_files $uri =404; expires 7d; }
    location ~ /\\. { deny all; }
${renderRedirectLocations()}
}
`;
}

export async function buildSite({ siteUrl = '', outDir = path.join(projectRoot, 'dist') } = {}) {
  const origin = normalizeSiteUrl(siteUrl);
  const publicDir = path.join(outDir, 'public');
  await mkdir(path.join(publicDir, 'img', 'brands'), { recursive: true });
  // Copy an explicit allowlist, never the whole workspace or original image directory.
  for (const file of publicFiles.filter(file => file !== 'index.html')) {
    await copyFile(path.join(projectRoot, file), path.join(publicDir, file));
  }
  const source = await readFile(path.join(projectRoot, 'index.html'), 'utf8');
  await writeFile(path.join(publicDir, 'index.html'), renderHtml(source, origin));
  await writeFile(path.join(outDir, 'nginx.conf'), renderNginx(origin));
  await writeFile(path.join(outDir, 'baota-locations.conf'),
    '# Paste inside the existing website server block. Keep your SSL and root settings.\n' + renderRedirectLocations());
  await writeFile(path.join(publicDir, 'robots.txt'), origin
    ? `User-agent: *\nAllow: /\nDisallow: /go/\n\nSitemap: ${origin}/sitemap.xml\n`
    : 'User-agent: *\nDisallow: /\n');
  if (origin) {
    await writeFile(path.join(publicDir, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${origin}/</loc></url></urlset>\n`);
  } else {
    await unlink(path.join(publicDir, 'sitemap.xml')).catch(error => { if (error.code !== 'ENOENT') throw error; });
  }
  const allowed = new Set([...publicFiles, 'robots.txt', ...(origin ? ['sitemap.xml'] : [])]);
  const entries = await readdir(publicDir, { recursive: true, withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) continue;
    const relative = path.relative(publicDir, path.join(entry.parentPath, entry.name)).split(path.sep).join('/');
    if (!allowed.has(relative) || entry.isSymbolicLink()) throw new Error(`Unexpected public file; inspect before publishing: ${relative}`);
  }
  return { publicDir, origin, files: allowed.size };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    const result = await buildSite({ siteUrl: process.env.SITE_URL || '' });
    console.log(`Built ${result.files} files at ${result.publicDir}`);
    console.log(result.origin ? `Production SEO: ${result.origin}` : 'Preview mode: noindex. Set SITE_URL to your HTTPS domain for production.');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
